### PR TITLE
Fix broken link for guides from docs

### PR DESCRIPTION
**Pull request by colemanserious**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hmm, something missing here for sure, because that should probably not just link to the CLI info. 

Looking at commit logs...

**Comment by deadprogram** [comment]
Hi @colemanserious 

Commit 50114ee04e77c38103caf5b88de0e0ba2d64637b moved that information to `documentation/getting-started/index` can you please point there instead?

Thank you very much for noticing the error.

**Comment by colemanserious** [comment]
Hi @deadprogram - just noticed your comment - revisiting my fix to take into account 50114ee

**Comment by colemanserious** [comment]
Hmmm - if I point to documentation/getting-started/index, your user will drop out of the Guides section, and bounce into another, which feels odd, navigationally.  However, the 'What Is Gobot' fits very nicely in  'Getting Started'.  Seems cleaner to (1) revert commit 6422202, and (2) thus point to CLI as the starting guide, until we add others. Agreed?

**Comment by deadprogram** [comment]
It is a logical suggestion, but seems like dropping them to the CLI docs page as the initial starting point is not very friendly. The spirit of going to "What Is Gobot?" as the getting started destination still seems like the best approach, IMO. Does that makes sense to you as well?

**Comment by colemanserious** [comment]
Hmm - remember, getting started still goes to 'What is Gobot', and I'd count getting started as the initial starting point.  Question is only whether 'what is gobot' is a guide and warrants a guide entry.   I'd argue it doesn't, and propose to keep with the commit as it is.  But...  not dogmatic about it.  Pick a path, and I'll make it happen.

**Comment by deadprogram** [comment]
I see what you mean, and works for me. We may need more guides at some point, but that is something else.

Merging, and thanks!

**Pull request merged**
