### PR TITLE
Minor fixes and explanation

### PR DESCRIPTION
**Pull request by trevrosen**
**(Advance apologies: this is the last time I'll blend minor typo fixes w/ larger rearrangement requests)**

## Minor Changes
- Fix an instance of "it's" where "its" was what was really meant ("it's" is a contraction and not a possessive).
- Capitalize "Arduino" on main docs page
- Make front page "the Go programming language" into a link (since it already looked like one due to span styling).

## Major(ish) Changes
This PR removes "About Gobot" from the Guides submenu (where it didn't really seem to belong w/ the other technical guides) and instead moves that content to the top of Getting Started.

I've also added an explanatory list attempting to encapsulate the major abstractions and capabilities of Gobot as tightly as possible.

I've opened #34 so that we can discuss/iterate on some similar improvements in this vein.

### CODE REVIEW

**Comment by trevrosen** [comment]
Blergh got mixed up and was sloppy on commit messages: 9160a67 is the one with the extra summary section.

**Comment by zankich** [comment]
@trevrosen thanks for the PR! The reorganization is small in this case,  so I'll merge, but in the future can you please create a separate PR for content and navigation changes. That way we can discuss more substantial layout changes without  the content changes getting hung up!

**Comment by zankich** [comment]
:icecream:

**Comment by trevrosen** [comment]
Yeah absolutely. Would’ve done that this time but was kind of caught up in GopherCon stuff and forgot what I had done where/when.

**Pull request merged**
